<?php

namespace App\Constants;

class StatusCode
{
  const OK = 'OK';
  const CREATED = 'CREATED';
  const ACCEPTED = 'ACCEPTED';
  const NOT_MODIFIED = 'NOT_MODIFIED';
  const TEMPORARY_REDIRECT = 'TEMPORARY_REDIRECT';
  const BAD_REQUEST = 'BAD_REQUEST';
  const UNAUTHORIZED = 'UNAUTHORIZED';
  const FORBIDDEN = 'FORBIDDEN';
  const NOT_FOUND = 'NOT_FOUND';
  const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
  const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
  const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
  const INTERNAL_ERROR = 'INTERNAL_SERVER_ERROR';
  const BAD_GATEWAY = 'BAD_GATEWAY';
  const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
  const GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT';
}
